INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_IMPULSE_SENDER', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '发号器序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ATTACHMENT_CHILD', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '附件子表信息序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('RM_USER', sysdate(), '3', 0, null, '4003%tY%tm%td%value', 7, '用户表序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ACCESSORIES_LIST', sysdate(), '3', 0, null, '4004%tY%tm%td%value', 7, '附件表序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_BANK_CARD_RECORD', sysdate(), '3', 0, null, '4005%tY%tm%td%value', 7, '客户关联银行卡换卡记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_CONTRACT', sysdate(), '3', 0, null, '4006%tY%tm%td%value', 7, '合同版本管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WEALTH_MANAGE_POST', sysdate(), '3', 0, null, '4007%tY%tm%td%value', 7, '理财经理调岗管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CUSTOMER_BANK_CARDS', sysdate(), '3', 0, null, '4008%tY%tm%td%value', 7, '客户关联银行记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_DISTRIBUTION_DETAIL', sysdate(), '3', 0, null, '4009%tY%tm%td%value', 7, '分配明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_DISTRIBUTION_CLIENT', sysdate(), '3', 0, null, '4010%tY%tm%td%value', 7, '客户重新分配功能序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WEALTH_MANAGERS_LEAVE', sysdate(), '3', 0, null, '4011%tY%tm%td%value', 7, '理财经理离职管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_EMPLOYEES', sysdate(), '3', 0, null, '4012%tY%tm%td%value', 7, '人员管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_FINANCIAL_PAYMENT', sysdate(), '3', 0, null, '4013%tY%tm%td%value', 7, '财务付款管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_EARNINGS', sysdate(), '3', 0, null, '4014%tY%tm%td%value', 7, '收益管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ORDERS', sysdate(), '3', 0, null, '4015%tY%tm%td%value', 7, '订单管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_PRODUCT_DISCLOSURE', sysdate(), '3', 0, null, '4016%tY%tm%td%value', 7, '产品信息披露序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_PRODUCT', sysdate(), '3', 0, null, '4017%tY%tm%td%value', 7, '产品定义序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_COMMUNICATION_RECORD', sysdate(), '3', 0, null, '4018%tY%tm%td%value', 7, '客户沟通记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CUSTOMER', sysdate(), '3', 0, null, '4019%tY%tm%td%value', 7, '客户基本信息序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ATTACHMENT_CHILD', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '附件子表信息序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('RM_USER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '用户表序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ACCESSORIES_LIST', sysdate(), '3', 0, null, '4003%tY%tm%td%value', 7, '附件表序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_BANK_CARD_RECORD', sysdate(), '3', 0, null, '4004%tY%tm%td%value', 7, '客户关联银行卡换卡记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_CONTRACT', sysdate(), '3', 0, null, '4005%tY%tm%td%value', 7, '合同版本管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WEALTH_MANAGE_POST', sysdate(), '3', 0, null, '4006%tY%tm%td%value', 7, '理财经理调岗管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CUSTOMER_BANK_CARDS', sysdate(), '3', 0, null, '4007%tY%tm%td%value', 7, '客户关联银行记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_DISTRIBUTION_DETAIL', sysdate(), '3', 0, null, '4008%tY%tm%td%value', 7, '分配明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_DISTRIBUTION_CLIENT', sysdate(), '3', 0, null, '4009%tY%tm%td%value', 7, '客户重新分配功能序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WEALTH_MANAGERS_LEAVE', sysdate(), '3', 0, null, '4010%tY%tm%td%value', 7, '理财经理离职管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_EMPLOYEES', sysdate(), '3', 0, null, '4011%tY%tm%td%value', 7, '人员管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_FINANCIAL_PAYMENT', sysdate(), '3', 0, null, '4012%tY%tm%td%value', 7, '财务付款管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_EARNINGS', sysdate(), '3', 0, null, '4013%tY%tm%td%value', 7, '收益管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ORDERS', sysdate(), '3', 0, null, '4014%tY%tm%td%value', 7, '订单管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_PRODUCT_DISCLOSURE', sysdate(), '3', 0, null, '4015%tY%tm%td%value', 7, '产品信息披露序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_PRODUCT', sysdate(), '3', 0, null, '4016%tY%tm%td%value', 7, '产品定义序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_COMMUNICATION_RECORD', sysdate(), '3', 0, null, '4017%tY%tm%td%value', 7, '客户沟通记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CUSTOMER', sysdate(), '3', 0, null, '4018%tY%tm%td%value', 7, '客户基本信息序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ATTACHMENT_CHILD', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '附件子表信息序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('RM_USER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '用户表序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ACCESSORIES_LIST', sysdate(), '3', 0, null, '4003%tY%tm%td%value', 7, '附件表序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_BANK_CARD_RECORD', sysdate(), '3', 0, null, '4004%tY%tm%td%value', 7, '客户关联银行卡换卡记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_CONTRACT', sysdate(), '3', 0, null, '4005%tY%tm%td%value', 7, '合同版本管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WEALTH_MANAGE_POST', sysdate(), '3', 0, null, '4006%tY%tm%td%value', 7, '理财经理调岗管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CUSTOMER_BANK_CARDS', sysdate(), '3', 0, null, '4007%tY%tm%td%value', 7, '客户关联银行记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_DISTRIBUTION_DETAIL', sysdate(), '3', 0, null, '4008%tY%tm%td%value', 7, '分配明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_DISTRIBUTION_CLIENT', sysdate(), '3', 0, null, '4009%tY%tm%td%value', 7, '客户重新分配功能序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WEALTH_MANAGERS_LEAVE', sysdate(), '3', 0, null, '4010%tY%tm%td%value', 7, '理财经理离职管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_EMPLOYEES', sysdate(), '3', 0, null, '4011%tY%tm%td%value', 7, '人员管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_FINANCIAL_PAYMENT', sysdate(), '3', 0, null, '4012%tY%tm%td%value', 7, '财务付款管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_EARNINGS', sysdate(), '3', 0, null, '4013%tY%tm%td%value', 7, '收益管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_ORDERS', sysdate(), '3', 0, null, '4014%tY%tm%td%value', 7, '订单管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_PRODUCT_DISCLOSURE', sysdate(), '3', 0, null, '4015%tY%tm%td%value', 7, '产品信息披露序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUSINESS_PRODUCT', sysdate(), '3', 0, null, '4016%tY%tm%td%value', 7, '产品定义序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_COMMUNICATION_RECORD', sysdate(), '3', 0, null, '4017%tY%tm%td%value', 7, '客户沟通记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CUSTOMER', sysdate(), '3', 0, null, '4018%tY%tm%td%value', 7, '客户基本信息序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('WK_TASK_NODE_EXT_CONF', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '任务节点扩展配置序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('WK_FORM_TEMPLATE', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '表单模板序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('WK_TASK_NODE_EXT_CONF', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '任务节点扩展配置序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('WK_FORM_TEMPLATE', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '表单模板序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('WK_TASK_NODE_EXT_CONF', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '任务节点扩展配置序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('WK_FORM_TEMPLATE', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '表单模板序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_CHANGE_PLAN', sysdate(), '3', 0, null, '4001%tY%tm%td%value', 7, '变车管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WAREHOUSE_GATE', sysdate(), '3', 0, null, '4002%tY%tm%td%value', 7, '仓库门号序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_WAREHOUSE_POSITION', sysdate(), '3', 0, null, '4003%tY%tm%td%value', 7, '仓位号序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CAR', sysdate(), '3', 0, null, '4004%tY%tm%td%value', 7, '车辆信息序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_PURCHASE_INTENTION', sysdate(), '3', 0, null, '4005%tY%tm%td%value', 7, '购买意向管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_PAYMENT_MODE', sysdate(), '3', 0, null, '4006%tY%tm%td%value', 7, '收款方式序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_GATE', sysdate(), '3', 0, null, '4007%tY%tm%td%value', 7, '门岗序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_SHIP_MODE', sysdate(), '3', 0, null, '4008%tY%tm%td%value', 7, '发运方式序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER_PRODUCT_DETAIL', sysdate(), '3', 0, null, '4009%tY%tm%td%value', 7, '销售订单产品明细序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_DISTRIBUTION_PLAN', sysdate(), '3', 0, null, '4010%tY%tm%td%value', 7, '配送计划序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_PRODUCT_BATCH_NUMBER', sysdate(), '3', 0, null, '4011%tY%tm%td%value', 7, '产品批次记录序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_LOADING_NOTICE', sysdate(), '3', 0, null, '4012%tY%tm%td%value', 7, '装车通知单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_FREIGHT', sysdate(), '3', 0, null, '4013%tY%tm%td%value', 7, '运费维护序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_TRAIN_STATION', sysdate(), '3', 0, null, '4014%tY%tm%td%value', 7, '火车站点序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_REQUISITION_WAREHOUSE', sysdate(), '3', 0, null, '4015%tY%tm%td%value', 7, '调拨库序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_LOGISTICS_COST_SETTLEMENT', sysdate(), '3', 0, null, '4016%tY%tm%td%value', 7, '物流费用结算审批单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_TRAINS_REQUISITION_PLAN', sysdate(), '3', 0, null, '4017%tY%tm%td%value', 7, '铁运调拨计划序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_CAR_REQUISITION_PLAN', sysdate(), '3', 0, null, '4018%tY%tm%td%value', 7, '汽运调拨计划序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_CAR_DISTRIBUTION_PLAN', sysdate(), '3', 0, null, '4019%tY%tm%td%value', 7, '汽运配送计划序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_VEHICLE_SAFETY_INSPECTION', sysdate(), '3', 0, null, '4020%tY%tm%td%value', 7, '车辆安全检查序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_REGION', sysdate(), '3', 0, null, '4021%tY%tm%td%value', 7, '区域维护序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_FLOW_TO', sysdate(), '3', 0, null, '4022%tY%tm%td%value', 7, '流向序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_RECEIPT_ADDRESS', sysdate(), '3', 0, null, '4023%tY%tm%td%value', 7, '收货地址维护序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_SHIPPER', sysdate(), '3', 0, null, '4024%tY%tm%td%value', 7, '发货方维护序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ROW_NUMBER', sysdate(), '3', 0, null, '4025%tY%tm%td%value', 7, '排号表序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_CUSTOMER_AVAILABLE_AMOUNT', sysdate(), '3', 0, null, '4026%tY%tm%td%value', 7, '客户业务可用金额序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_FINANCIAL_BOOK_VALUE', sysdate(), '3', 0, null, '4027%tY%tm%td%value', 7, '客户财务账面金额序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_BUSINESS_USABLE_CHANGE', sysdate(), '3', 0, null, '4028%tY%tm%td%value', 7, '业务可用额变动序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_RECEIPT_CONF_LETTER', sysdate(), '3', 0, null, '4029%tY%tm%td%value', 7, '收货确认函序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_CREDIT_MANAGER', sysdate(), '3', 0, null, '4030%tY%tm%td%value', 7, '授信管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_COLLECTION_MANAGEMENT', sysdate(), '3', 0, null, '4031%tY%tm%td%value', 7, '收款管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ACC_CUSTOMER_BALANCE_CHANGE', sysdate(), '3', 0, null, '4032%tY%tm%td%value', 7, '客户余额变动序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_WEIGHING_BILL', sysdate(), '3', 0, null, '4033%tY%tm%td%value', 7, '过磅单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_LADING_BILL', sysdate(), '3', 0, null, '4034%tY%tm%td%value', 7, '司机提货单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BUS_ORDER', sysdate(), '3', 0, null, '4035%tY%tm%td%value', 7, '销售订单序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_PRODUCT_TYPE', sysdate(), '3', 0, null, '4036%tY%tm%td%value', 7, '产品类别序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_LOGISTICS_COMPANY', sysdate(), '3', 0, null, '4037%tY%tm%td%value', 7, '物流公司序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_PRICE', sysdate(), '3', 0, null, '4038%tY%tm%td%value', 7, '价格管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_PRODUCT', sysdate(), '3', 0, null, '4039%tY%tm%td%value', 7, '产品管理序列，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('BASE_CUSTOMER', sysdate(), '3', 0, null, '4040%tY%tm%td%value', 7, '客户管理序列，每天从1开始');


INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('ORDER_NUM', TIMESTAMP '2016-01-02 12:12:12', '3', 0, null, 'O%tY%tm%td%value',4, '销售订单编号，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('CAR_DISTRIBUTION_PLAN_CODE', TIMESTAMP '2016-01-02 12:12:12', '3', 0, null, 'D%tY%tm%td%value',4, '汽运配送计划单号，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('CAR_REQUISITION_PLAN_CODE', TIMESTAMP '2016-01-02 12:12:12', '3', 0, null, 'R%tY%tm%td%value',4, '汽运调拨计划单号，每天从1开始');
INSERT INTO BASE_IMPULSE_SENDER (SEQUENCE_NAME, UPDATE_DATE, CYCLE_TYPE, CURRENT_VALUE, CURRENT_FMT_VALUE, SEQUENCE_RULE, SEQUENCE_LEN, REMARK) 
VALUES ('TRAINS_PLAN_CODE', TIMESTAMP '2016-01-02 12:12:12', '3', 0, null, 'T%tY%tm%td%value',4, '铁运调拨计划单号，每天从1开始');

